version: '3.0'
services:
  becam:
    build:
      context: ./becam
      args:
        environment: "dev"
    container_name: 'becam-development'
    stdin_open: true
    tty: true
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - env/dev.env
    ports:
      - "10000:10000"
    volumes:
      - './becam/project/:/home/develop'
    command: /bin/bash -c 'sleep 5; flask run --host 0.0.0.0 --port 10000'

  socket:
    build:
      context: ./becam
      args:
        environment: "dev"
    container_name: 'socket-development'
    stdin_open: true
    tty: true
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - env/dev.env
    volumes:
      - './becam/project/:/home/develop'
    command: /bin/bash -c 'sleep 10; python -m app.tcp_client'

  socket_server:
    build:
      context: ./becam
      args:
        environment: "dev"
    container_name: 'socketserver-development'
    stdin_open: true
    tty: true
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - env/dev.env
    ports:
      - "9999:9999"
    volumes:
      - './becam/project/:/home/develop'
    command: /bin/bash -c 'sleep 5; python -m app.tcp_server'