version: '3'
services:
  becam_prod:
    image: jimyfc/becam-backend:latest
    stdin_open: true
    tty: true
    build:
      context: ./becam
      args:
        environment: "prod"
    container_name: becam-prod
    ports:
      - "8000:8000"
    volumes:
      - ./becam/project:/home/develop
      - ./logs:/logs
      - prop-becam:/tmp/
      - static-becam:/var/www/apibecam.becheckin.com/
    env_file:
      - env/prod.env
    command: gunicorn --workers=5 --threads=2 --log-level=error --access-logfile /logs/access.log  --error-logfile /logs/error.log, --log-file /logs/gunicorn.log -b unix:/tmp/becam.sock manage:app --preload
    restart: unless-stopped

  becam_nginx:
    image: jimyfc/becam:latest
    stdin_open: true
    tty: true
    build:
      context: ./nginx
      args:
        environment: "prod"
    container_name: becam_nginx_production
    volumes:
      - prop-becam:/tmp
      - static-becam:/var/www/apibecam.becheckin.com/
      - ./logs:/logs
      - ./becam/app:/home/develop
      # - /etc/letsencrypt/live/becam.com/fullchain.pem:/etc/letsencrypt/live/becam.com/fullchain.pem
      # - /etc/letsencrypt/live/becam.com/privkey.pem:/etc/letsencrypt/live/becam.com/privkey.pem
      # - ./build:/home/ubuntu/becam-backend/build/
    ports:
      - "80:80"
      # - "443:443"
    env_file:
      - env/prod.env
    restart: unless-stopped

  socket_client_prod:
    image: jimyfc/socket_client:latest
    build:
      context: ./becam_client
      args:
        environment: "prod"
    container_name: 'socket-production'
    stdin_open: true
    tty: true
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - env/prod.env
    volumes:
      - './becam_client/client:/home/develop'
    command: /bin/sh -c 'sleep 10; python -m tcp_client'

  socket_server_prod:
    image: jimyfc/socket_server:latest
    build:
      context: ./becam_server
      args:
        environment: "prod"
    container_name: 'socketserver-production'
    stdin_open: true
    tty: true
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - env/prod.env
    ports:
      - "9999:9999"
    volumes:
      - './becam_server/server:/home/develop'
    command: /bin/sh -c 'sleep 5; python -m tcp_server'

volumes:
  prop-becam:
  static-becam:
