FROM nginx:1.16.0
LABEL maintainer="jfalconcardenas@gmail.com" 

ARG environment

#Crea la sites-enable
RUN mkdir /etc/nginx/sites-enabled

# Se hace copy de los sitios enables

COPY /sites-available/becam_${environment}.conf /etc/nginx/sites-available/
RUN  ln -s /etc/nginx/sites-available/*  /etc/nginx/sites-enabled/
COPY nginx.conf /etc/nginx/nginx.conf
